### ISSUE TITLE
[Bug] Ending a call with a wired headset or bluetooth doesn't stop the recording

### ISSUE THREAD

**Issue by WildS0ft** [harv/XRecorder#8] opened 2016-07-07 08:25 UTC
Ending a call with a wired headset or bluetooth doesn't stop the recording. If you don't manually stop the recording immediately, it continues on and forces you to reboot the device. It previously worked in earlier releases.

**Comment by WildS0ft** [comment] 2016-10-18 21:59
@harv any news?

**Comment by harv** [comment] 2016-10-25 12:12
I have no headset can answer or end the call by clicking a key.
And with a normal earbud, the problem can not reproduce.
So, the problem is postponed and may be fixed in the future. Sorry.

**Comment by WildS0ft** [comment] 2016-10-27 11:12
@harv I understand it would be difficult to fix without a headset. But would you please consider to find one? Any old cheap headset will do as long as it has a button. Or perhaps just take another look at the latest code? This bug is really debilitating, especially while I'm driving. I like your mod and the functionality it adds and would really appreciate it if you'd take another look. No other mods can do what this does.

The bug was introduced in 2.1.2. **It's working fine in 2.1.1**.
(Also there is no version 2.1.2 in the [release list](https://github.com/harv/XRecorder/releases))

Perhaps this will help:
**OS:** Android 5.1.1 (Lollipop)
**Device:** Sony Xperia Z1 Compact (D5503)
**Firmware:** 14.6.A.1.236
**Xposed version:** 86
**Call Recorder app used:** [CallRecorderAPK.zip](https://github.com/harv/XRecorder/files/555431/CallRecorderAPK.zip) from [this XDA thread](http://forum.xda-developers.com/showpost.php?p=60656378&postcount=50) ([VirusTotal Scan](https://www.virustotal.com/en/file/f4c5f5efa5130c1e5e91f9f51c18cdd51b1e0317433fce546110e31253487860/analysis/1477564490/))
**Call Recorder app location (manual installation):** /system/priv-app/CallRecording/CallRecording.apk
**Phone setting call recorder:** Off

XRecorder settings:
**Enable auto call recording:** On
**Record outgoing call:** On
**Record incoming call:** On
**File name pattern:** ddMMyyyy-HHmmss-nn_pp-(tt)
**Custom Call Type:** incoming/outgoing
**Optimized display caller name:** On
**Enable Logging:** On

No Xposed logs generated.

Despite it saying `E/CallRecordingService(PID): CallItems.apk is missing. The call recording could not be saved.` in all the logs, it will still save the .amr.

**Logcat _NOT_ using headset button (v2.1.2l):**
```
D/CallRecordingService(25093): ACTION_CALL_STARTED
I/Xposed  (25093): [XRecorder]start recording
D/CallRecordingService(25093): Changing state - IDLE -> STARTING
W/AudioFlinger(  627): acquireAudioSessionId() unknown client 25093 for session 871
D/CallRecordingService(25093): Changing state - STARTING -> RECORDING
D/CallRecordingService(25093): ACTION_CALL_STARTED
I/Xposed  (25093): [XRecorder]end recording
D/CallRecordingService(25093): Changing state - RECORDING -> STOPPING
W/AudioFlinger(  627): session id 871 not found for pid 25093
D/CallRecordingService(25093): Adding file path: /storage/emulated/0/CallRecorder/DATE-TIME-NAME_NUMBER-(outgoing).amr
D/CallRecordingService(25093): Changing state - STOPPING -> LINGERING
E/ActivityThread(25093): Failed to find provider info for com.sonymobile.callitems
E/CallRecordingService(25093): CallItems.apk is missing. The call recording could not be saved. Please check system composition: Unknown URL content://com.sonymobile.callitems/call_items/11026
D/CallRecordingService(25093): Changing state - LINGERING -> IDLE
W/CallRecording(25093): onReceive: unknown intent: com.sonymobile.callwidgetframework.WIDGET_ACTION_DESTROYED
```
**Logcat using headset button (v2.1.2):**
```
D/CallRecordingService(25093): ACTION_CALL_STARTED
I/Xposed  (25093): [XRecorder]start recording
D/CallRecordingService(25093): Changing state - IDLE -> STARTING
W/AudioFlinger(  627): acquireAudioSessionId() unknown client 25093 for session 884
D/CallRecordingService(25093): Changing state - STARTING -> RECORDING
D/CallRecordingService(25093): ACTION_CALL_STARTED
W/CallRecording(25093): onReceive: unknown intent: com.sonymobile.callwidgetframework.WIDGET_ACTION_FOCUSCHANGE
W/CallRecording(25093): onReceive: unknown intent: com.sonymobile.callwidgetframework.WIDGET_ACTION_DESTROYED
```
**Logcat using headset button and after call ends manually stop recording (v2.1.2):**
```
D/CallRecordingService(25093): ACTION_CALL_STARTED
I/Xposed  (25093): [XRecorder]start recording
D/CallRecordingService(25093): Changing state - IDLE -> STARTING
W/AudioFlinger(  627): acquireAudioSessionId() unknown client 25093 for session 946
D/CallRecordingService(25093): Changing state - STARTING -> RECORDING
D/CallRecordingService(25093): ACTION_CALL_STARTED
W/CallRecording(25093): onReceive: unknown intent: com.sonymobile.callwidgetframework.WIDGET_ACTION_FOCUSCHANGE
W/CallRecording(25093): onReceive: unknown intent: com.sonymobile.callwidgetframework.WIDGET_ACTION_DESTROYED
D/CallRecordingService(25093): ACTION_STOP_RECORDING
D/CallRecordingService(25093): Changing state - RECORDING -> STOPPING
I/Xposed  (25093): [XRecorder]end recording(manual)
W/AudioFlinger(  627): session id 946 not found for pid 25093
D/CallRecordingService(25093): Adding file path: /storage/emulated/0/CallRecorder/DATE-TIME-NAME_NUMBER-(outgoing).amr
D/CallRecordingService(25093): Changing state - STOPPING -> LINGERING
E/ActivityThread(25093): Failed to find provider info for com.sonymobile.callitems
E/CallRecordingService(25093): CallItems.apk is missing. The call recording could not be saved. Please check system composition: Unknown URL content://com.sonymobile.callitems/call_items/11031
D/CallRecordingService(25093): Changing state - LINGERING -> IDLE
```
**If you unplug the headset/disconnect bluetooth before manually ending the recording, it cannot be stopped. The stop button on the notification does nothing and the device needs to be rebooted.**

**Logcat using headset button on version 2.1.1 (Working):**
```
D/CallRecordingService(22414): ACTION_CALL_STARTED
I/Xposed  (22414): [XRecorder]start recording
D/CallRecordingService(22414): Changing state - IDLE -> STARTING
W/AudioFlinger(  629): acquireAudioSessionId() unknown client 22414 for session 78
D/CallRecordingService(22414): Changing state - STARTING -> RECORDING
D/CallRecordingService(22414): ACTION_CALL_STARTED
I/Xposed  (22414): [XRecorder]end recording
D/CallRecordingService(22414): Changing state - RECORDING -> STOPPING
W/AudioFlinger(  629): session id 78 not found for pid 22414
D/CallRecordingService(22414): Adding file path: /storage/emulated/0/CallRecorder/DATE-TIME-NAME_NUMBER-(outgoing).amr
D/CallRecordingService(22414): Changing state - STOPPING -> LINGERING
E/ActivityThread(22414): Failed to find provider info for com.sonymobile.callitems
E/CallRecordingService(22414): CallItems.apk is missing. The call recording could not be saved. Please check system composition: Unknown URL content://com.sonymobile.callitems/call_items/11042
D/CallRecordingService(22414): Changing state - LINGERING -> IDLE
W/CallRecording(22414): onReceive: unknown intent: com.sonymobile.callwidgetframework.WIDGET_ACTION_DESTROYED
```

**Closed** 2016-10-29 03:42 UTC

**Comment by harv** [comment] 2016-10-29 03:52
fixed. Please update in Xposed installer.
